name: example07
on: [push]
jobs:
    Test1:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "::error Intentional Error::missing semicolon" 
                # exit 1
       steps: 
            - run: |
                echo "::summary 100 resources created ::Missing semicolon"