name: example04
on: [push]
jobs: 
    Test1: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was automatically triggered by a ${{github.event_name}}"
    Test2: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was triggered by push event"
    Test3:
        runs-on: ubuntu-latest
        steps:
            - run: echo "3rd job"